#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

# wgodot-changes::begin
import wgodot_gd.deadcode_builders as wgodot_deadcode_builders
# wgodot-changes::end

env_gdscript = env_modules.Clone()

# wgodot-changes::begin
wgodot_deadcode_header = env_gdscript.CommandNoCache(
    "wgodot_gd/deadcode.gen.h",
    Glob("wgodot_gd/deadcode/in_class/deadcode*.txt"),
    env.Run(wgodot_deadcode_builders.make_deadcode_header),
)
# wgodot-changes::end

env_gdscript.add_source_files(env.modules_sources, "*.cpp")
# wgodot-changes::begin
env_gdscript.add_source_files(env.modules_sources, "./wgodot_gd/*.cpp")
env_gdscript.Depends(env.modules_sources, wgodot_deadcode_header)
# wgodot-changes::end

if env.editor_build:
    env_gdscript.add_source_files(env.modules_sources, "./editor/*.cpp")

    SConscript("editor/script_templates/SCsub")

    # Those two modules are required for the language server protocol
    if env["module_jsonrpc_enabled"] and env["module_websocket_enabled"]:
        env_gdscript.add_source_files(env.modules_sources, "./language_server/*.cpp")
    else:
        # Using a define in the disabled case, to avoid having an extra define
        # in regular builds where all modules are enabled.
        env_gdscript.Append(CPPDEFINES=["GDSCRIPT_NO_LSP"])
        # Also needed in main env to unexpose --lsp-port option.
        env.Append(CPPDEFINES=["GDSCRIPT_NO_LSP"])


if env["tests"]:
    # TODO: Handle test creation magic without needing to pass macro.
    env_gdscript.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_gdscript.add_source_files(env.modules_sources, "./tests/*.cpp")
