#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import make_virtuals

# wgodot-changes::begin
env.CommandNoCache("gdvirtual.gen.h", ["make_virtuals.py", "wgodot_native_virtuals.py"], env.Run(make_virtuals.run))
# wgodot-changes::end

env.add_source_files(env.core_sources, "*.cpp")
