// wgodot-changes::file
#include "wgodot_cpp_emitter.h"
#include "wgodot_cpp_names.h"

int WGodotCppEmitter::resource_index(const Resource *p_resource) {
	const String path = p_resource->get_path();
	if (const int *index = preload_indices.getptr(path)) {
		return *index;
	}
	int index = preloads.size();
	preloads.push_back({ path, p_resource->get_class(), false });
	preload_indices.insert(path, index);
	return index;
}

void WGodotCppEmitter::collect_resource_indices(const Variant &p_value, HashSet<int> &r_indices) {
	if (p_value.get_type() == Variant::OBJECT) {
		const Resource *resource = Object::cast_to<Resource>(static_cast<Object *>(p_value));
		if (resource && !Object::cast_to<Script>(resource)) {
			r_indices.insert(resource_index(resource));
		}
	} else if (p_value.get_type() == Variant::ARRAY) {
		const Array values = p_value;
		for (const Variant &value : values) {
			collect_resource_indices(value, r_indices);
		}
	} else if (p_value.get_type() == Variant::DICTIONARY) {
		const Dictionary values = p_value;
		for (const KeyValue<Variant, Variant> &entry : values) {
			collect_resource_indices(entry.key, r_indices);
			collect_resource_indices(entry.value, r_indices);
		}
	}
}

void WGodotCppEmitter::emit_preloads() {
	String source = "// wgodot-changes::file\n// Generated by WGodot. DO NOT EDIT MANUALLY.\n#include \"modules/wgodot/wgodot_preloads.h\"\n\n";
	if (!preloads.is_empty()) {
		source += "static const WGodotPreloads::Definition preloads[] = {\n";
		for (const auto &preload : preloads) {
			source += "\t{" + WGodotCppNames::quoted(preload.path) + ", " + WGodotCppNames::quoted(preload.type) + ", " + (preload.asynchronous ? "true" : "false") + "},\n";
		}
		source += "};\n\n";
	}
	source += "void register_main_game_preloads() {\n\tWGodotPreloads::set_manifest(" + String(preloads.is_empty() ? "nullptr" : "preloads") + ", " + itos(preloads.size()) + ");\n}\n";
	files.insert("game_preloads.cpp", source);
}
